name: Make BOATRACE forecast files

on:
  workflow_dispatch:
    inputs:
      jcd:
        description: "場コード"
        required: true
        default: "09"
      start_date:
        description: "初日 YYYYMMDD"
        required: true
        default: "20260415"
      prev_date:
        description: "前日 YYYYMMDD"
        required: true
        default: "20260419"
      final_date:
        description: "最終日 YYYYMMDD"
        required: true
        default: "20260420"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Show inputs
        run: |
          echo "jcd=${{ github.event.inputs.jcd }}"
          echo "start_date=${{ github.event.inputs.start_date }}"
          echo "prev_date=${{ github.event.inputs.prev_date }}"
          echo "final_date=${{ github.event.inputs.final_date }}"
